//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Legkaaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Животные.
    /// </summary>
    // *** Start programmer edit section *** (Животные CustomAttributes)

    // *** End programmer edit section *** (Животные CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЖивотныеE", new string[] {
            "НомерЖивотного as \'Номер животного\'",
            "Кличка as \'Кличка\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Ответственный\'"}, Hidden=new string[] {
            "Сотрудник.Фамилия"})]
    [AssociatedDetailViewAttribute("ЖивотныеE", "Сведения", "СведенияE", true, "", "Сведения", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЖивотныеE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ЖивотныеL", new string[] {
            "НомерЖивотного as \'Номер животного\'",
            "Кличка as \'Кличка\'",
            "Сотрудник.Фамилия as \'Ответственный\'"})]
    public class Животные : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЖивотного;
        
        private string fКличка;
        
        private IIS.Legkaaya.Сотрудник fСотрудник;
        
        private IIS.Legkaaya.DetailArrayOfСведения fСведения;
        
        // *** Start programmer edit section *** (Животные CustomMembers)

        // *** End programmer edit section *** (Животные CustomMembers)

        
        /// <summary>
        /// Кличка.
        /// </summary>
        // *** Start programmer edit section *** (Животные.Кличка CustomAttributes)

        // *** End programmer edit section *** (Животные.Кличка CustomAttributes)
        [StrLen(255)]
        public virtual string Кличка
        {
            get
            {
                // *** Start programmer edit section *** (Животные.Кличка Get start)

                // *** End programmer edit section *** (Животные.Кличка Get start)
                string result = this.fКличка;
                // *** Start programmer edit section *** (Животные.Кличка Get end)

                // *** End programmer edit section *** (Животные.Кличка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.Кличка Set start)

                // *** End programmer edit section *** (Животные.Кличка Set start)
                this.fКличка = value;
                // *** Start programmer edit section *** (Животные.Кличка Set end)

                // *** End programmer edit section *** (Животные.Кличка Set end)
            }
        }
        
        /// <summary>
        /// НомерЖивотного.
        /// </summary>
        // *** Start programmer edit section *** (Животные.НомерЖивотного CustomAttributes)

        // *** End programmer edit section *** (Животные.НомерЖивотного CustomAttributes)
        public virtual int НомерЖивотного
        {
            get
            {
                // *** Start programmer edit section *** (Животные.НомерЖивотного Get start)

                // *** End programmer edit section *** (Животные.НомерЖивотного Get start)
                int result = this.fНомерЖивотного;
                // *** Start programmer edit section *** (Животные.НомерЖивотного Get end)

                // *** End programmer edit section *** (Животные.НомерЖивотного Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.НомерЖивотного Set start)

                // *** End programmer edit section *** (Животные.НомерЖивотного Set start)
                this.fНомерЖивотного = value;
                // *** Start programmer edit section *** (Животные.НомерЖивотного Set end)

                // *** End programmer edit section *** (Животные.НомерЖивотного Set end)
            }
        }
        
        /// <summary>
        /// Животные.
        /// </summary>
        // *** Start programmer edit section *** (Животные.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Животные.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Legkaaya.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Животные.Сотрудник Get start)

                // *** End programmer edit section *** (Животные.Сотрудник Get start)
                IIS.Legkaaya.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Животные.Сотрудник Get end)

                // *** End programmer edit section *** (Животные.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.Сотрудник Set start)

                // *** End programmer edit section *** (Животные.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Животные.Сотрудник Set end)

                // *** End programmer edit section *** (Животные.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Животные.
        /// </summary>
        // *** Start programmer edit section *** (Животные.Сведения CustomAttributes)

        // *** End programmer edit section *** (Животные.Сведения CustomAttributes)
        public virtual IIS.Legkaaya.DetailArrayOfСведения Сведения
        {
            get
            {
                // *** Start programmer edit section *** (Животные.Сведения Get start)

                // *** End programmer edit section *** (Животные.Сведения Get start)
                if ((this.fСведения == null))
                {
                    this.fСведения = new IIS.Legkaaya.DetailArrayOfСведения(this);
                }
                IIS.Legkaaya.DetailArrayOfСведения result = this.fСведения;
                // *** Start programmer edit section *** (Животные.Сведения Get end)

                // *** End programmer edit section *** (Животные.Сведения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.Сведения Set start)

                // *** End programmer edit section *** (Животные.Сведения Set start)
                this.fСведения = value;
                // *** Start programmer edit section *** (Животные.Сведения Set end)

                // *** End programmer edit section *** (Животные.Сведения Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЖивотныеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖивотныеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖивотныеE", typeof(IIS.Legkaaya.Животные));
                }
            }
            
            /// <summary>
            /// "ЖивотныеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖивотныеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖивотныеL", typeof(IIS.Legkaaya.Животные));
                }
            }
        }
    }
}
