//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Legkaaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клетка.
    /// </summary>
    // *** Start programmer edit section *** (Клетка CustomAttributes)

    // *** End programmer edit section *** (Клетка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлеткаE", new string[] {
            "НомерКлетки as \'Номер клетки\'",
            "Тип as \'Тип\'",
            "Площадь as \'Площадь\'"})]
    [View("КлеткаL", new string[] {
            "НомерКлетки as \'Номер клетки\'",
            "Тип as \'Тип\'",
            "Площадь as \'Площадь\'"})]
    public class Клетка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКлетки;
        
        private string fТип;
        
        private string fПлощадь;
        
        // *** Start programmer edit section *** (Клетка CustomMembers)

        // *** End programmer edit section *** (Клетка CustomMembers)

        
        /// <summary>
        /// НомерКлетки.
        /// </summary>
        // *** Start programmer edit section *** (Клетка.НомерКлетки CustomAttributes)

        // *** End programmer edit section *** (Клетка.НомерКлетки CustomAttributes)
        public virtual int НомерКлетки
        {
            get
            {
                // *** Start programmer edit section *** (Клетка.НомерКлетки Get start)

                // *** End programmer edit section *** (Клетка.НомерКлетки Get start)
                int result = this.fНомерКлетки;
                // *** Start programmer edit section *** (Клетка.НомерКлетки Get end)

                // *** End programmer edit section *** (Клетка.НомерКлетки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клетка.НомерКлетки Set start)

                // *** End programmer edit section *** (Клетка.НомерКлетки Set start)
                this.fНомерКлетки = value;
                // *** Start programmer edit section *** (Клетка.НомерКлетки Set end)

                // *** End programmer edit section *** (Клетка.НомерКлетки Set end)
            }
        }
        
        /// <summary>
        /// Площадь.
        /// </summary>
        // *** Start programmer edit section *** (Клетка.Площадь CustomAttributes)

        // *** End programmer edit section *** (Клетка.Площадь CustomAttributes)
        [StrLen(255)]
        public virtual string Площадь
        {
            get
            {
                // *** Start programmer edit section *** (Клетка.Площадь Get start)

                // *** End programmer edit section *** (Клетка.Площадь Get start)
                string result = this.fПлощадь;
                // *** Start programmer edit section *** (Клетка.Площадь Get end)

                // *** End programmer edit section *** (Клетка.Площадь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клетка.Площадь Set start)

                // *** End programmer edit section *** (Клетка.Площадь Set start)
                this.fПлощадь = value;
                // *** Start programmer edit section *** (Клетка.Площадь Set end)

                // *** End programmer edit section *** (Клетка.Площадь Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Клетка.Тип CustomAttributes)

        // *** End programmer edit section *** (Клетка.Тип CustomAttributes)
        [StrLen(255)]
        public virtual string Тип
        {
            get
            {
                // *** Start programmer edit section *** (Клетка.Тип Get start)

                // *** End programmer edit section *** (Клетка.Тип Get start)
                string result = this.fТип;
                // *** Start programmer edit section *** (Клетка.Тип Get end)

                // *** End programmer edit section *** (Клетка.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клетка.Тип Set start)

                // *** End programmer edit section *** (Клетка.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Клетка.Тип Set end)

                // *** End programmer edit section *** (Клетка.Тип Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлеткаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлеткаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлеткаE", typeof(IIS.Legkaaya.Клетка));
                }
            }
            
            /// <summary>
            /// "КлеткаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлеткаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлеткаL", typeof(IIS.Legkaaya.Клетка));
                }
            }
        }
    }
}
