//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Legkaaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Корм.
    /// </summary>
    // *** Start programmer edit section *** (Корм CustomAttributes)

    // *** End programmer edit section *** (Корм CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КормE", new string[] {
            "КодКорма as \'Код корма\'",
            "Название as \'Название\'"})]
    [View("КормL", new string[] {
            "КодКорма as \'Код корма\'",
            "Название as \'Название\'"})]
    public class Корм : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодКорма;
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Корм CustomMembers)

        // *** End programmer edit section *** (Корм CustomMembers)

        
        /// <summary>
        /// КодКорма.
        /// </summary>
        // *** Start programmer edit section *** (Корм.КодКорма CustomAttributes)

        // *** End programmer edit section *** (Корм.КодКорма CustomAttributes)
        public virtual int КодКорма
        {
            get
            {
                // *** Start programmer edit section *** (Корм.КодКорма Get start)

                // *** End programmer edit section *** (Корм.КодКорма Get start)
                int result = this.fКодКорма;
                // *** Start programmer edit section *** (Корм.КодКорма Get end)

                // *** End programmer edit section *** (Корм.КодКорма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Корм.КодКорма Set start)

                // *** End programmer edit section *** (Корм.КодКорма Set start)
                this.fКодКорма = value;
                // *** Start programmer edit section *** (Корм.КодКорма Set end)

                // *** End programmer edit section *** (Корм.КодКорма Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Корм.Название CustomAttributes)

        // *** End programmer edit section *** (Корм.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Корм.Название Get start)

                // *** End programmer edit section *** (Корм.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Корм.Название Get end)

                // *** End programmer edit section *** (Корм.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Корм.Название Set start)

                // *** End programmer edit section *** (Корм.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Корм.Название Set end)

                // *** End programmer edit section *** (Корм.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КормE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КормE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КормE", typeof(IIS.Legkaaya.Корм));
                }
            }
            
            /// <summary>
            /// "КормL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КормL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КормL", typeof(IIS.Legkaaya.Корм));
                }
            }
        }
    }
}
