//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Legkaaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расписание.
    /// </summary>
    // *** Start programmer edit section *** (Расписание CustomAttributes)

    // *** End programmer edit section *** (Расписание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасписаниеE", new string[] {
            "ВремяУборки as \'Время уборки\'",
            "ВремяКормления as \'Время кормления\'",
            "Корм as \'Корм\'",
            "Корм.Название as \'Название\'",
            "Животные as \'Животные\'",
            "Животные.Кличка as \'Кличка\'",
            "Клетка as \'Клетка\'",
            "Клетка.НомерКлетки as \'Клетка\'"}, Hidden=new string[] {
            "Корм.Название",
            "Животные.Кличка"})]
    [MasterViewDefineAttribute("РасписаниеE", "Корм", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("РасписаниеE", "Животные", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Кличка")]
    [MasterViewDefineAttribute("РасписаниеE", "Клетка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Тип")]
    [View("РасписаниеL", new string[] {
            "ВремяУборки as \'Время уборки\'",
            "ВремяКормления as \'Время кормления\'",
            "Корм.Название as \'Название\'",
            "Животные.Кличка as \'Кличка\'",
            "Клетка.Тип as \'Тип\'"})]
    public class Расписание : ICSSoft.STORMNET.DataObject
    {
        
        private string fВремяУборки;
        
        private string fВремяКормления;
        
        private IIS.Legkaaya.Корм fКорм;
        
        private IIS.Legkaaya.Животные fЖивотные;
        
        private IIS.Legkaaya.Клетка fКлетка;
        
        // *** Start programmer edit section *** (Расписание CustomMembers)

        // *** End programmer edit section *** (Расписание CustomMembers)

        
        /// <summary>
        /// ВремяКормления.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.ВремяКормления CustomAttributes)

        // *** End programmer edit section *** (Расписание.ВремяКормления CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяКормления
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.ВремяКормления Get start)

                // *** End programmer edit section *** (Расписание.ВремяКормления Get start)
                string result = this.fВремяКормления;
                // *** Start programmer edit section *** (Расписание.ВремяКормления Get end)

                // *** End programmer edit section *** (Расписание.ВремяКормления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.ВремяКормления Set start)

                // *** End programmer edit section *** (Расписание.ВремяКормления Set start)
                this.fВремяКормления = value;
                // *** Start programmer edit section *** (Расписание.ВремяКормления Set end)

                // *** End programmer edit section *** (Расписание.ВремяКормления Set end)
            }
        }
        
        /// <summary>
        /// ВремяУборки.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.ВремяУборки CustomAttributes)

        // *** End programmer edit section *** (Расписание.ВремяУборки CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяУборки
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.ВремяУборки Get start)

                // *** End programmer edit section *** (Расписание.ВремяУборки Get start)
                string result = this.fВремяУборки;
                // *** Start programmer edit section *** (Расписание.ВремяУборки Get end)

                // *** End programmer edit section *** (Расписание.ВремяУборки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.ВремяУборки Set start)

                // *** End programmer edit section *** (Расписание.ВремяУборки Set start)
                this.fВремяУборки = value;
                // *** Start programmer edit section *** (Расписание.ВремяУборки Set end)

                // *** End programmer edit section *** (Расписание.ВремяУборки Set end)
            }
        }
        
        /// <summary>
        /// Расписание.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.Животные CustomAttributes)

        // *** End programmer edit section *** (Расписание.Животные CustomAttributes)
        [PropertyStorage(new string[] {
                "Животные"})]
        [NotNull()]
        public virtual IIS.Legkaaya.Животные Животные
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.Животные Get start)

                // *** End programmer edit section *** (Расписание.Животные Get start)
                IIS.Legkaaya.Животные result = this.fЖивотные;
                // *** Start programmer edit section *** (Расписание.Животные Get end)

                // *** End programmer edit section *** (Расписание.Животные Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.Животные Set start)

                // *** End programmer edit section *** (Расписание.Животные Set start)
                this.fЖивотные = value;
                // *** Start programmer edit section *** (Расписание.Животные Set end)

                // *** End programmer edit section *** (Расписание.Животные Set end)
            }
        }
        
        /// <summary>
        /// Расписание.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.Клетка CustomAttributes)

        // *** End programmer edit section *** (Расписание.Клетка CustomAttributes)
        [PropertyStorage(new string[] {
                "Клетка"})]
        [NotNull()]
        public virtual IIS.Legkaaya.Клетка Клетка
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.Клетка Get start)

                // *** End programmer edit section *** (Расписание.Клетка Get start)
                IIS.Legkaaya.Клетка result = this.fКлетка;
                // *** Start programmer edit section *** (Расписание.Клетка Get end)

                // *** End programmer edit section *** (Расписание.Клетка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.Клетка Set start)

                // *** End programmer edit section *** (Расписание.Клетка Set start)
                this.fКлетка = value;
                // *** Start programmer edit section *** (Расписание.Клетка Set end)

                // *** End programmer edit section *** (Расписание.Клетка Set end)
            }
        }
        
        /// <summary>
        /// Расписание.
        /// </summary>
        // *** Start programmer edit section *** (Расписание.Корм CustomAttributes)

        // *** End programmer edit section *** (Расписание.Корм CustomAttributes)
        [PropertyStorage(new string[] {
                "Корм"})]
        [NotNull()]
        public virtual IIS.Legkaaya.Корм Корм
        {
            get
            {
                // *** Start programmer edit section *** (Расписание.Корм Get start)

                // *** End programmer edit section *** (Расписание.Корм Get start)
                IIS.Legkaaya.Корм result = this.fКорм;
                // *** Start programmer edit section *** (Расписание.Корм Get end)

                // *** End programmer edit section *** (Расписание.Корм Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расписание.Корм Set start)

                // *** End programmer edit section *** (Расписание.Корм Set start)
                this.fКорм = value;
                // *** Start programmer edit section *** (Расписание.Корм Set end)

                // *** End programmer edit section *** (Расписание.Корм Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасписаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасписаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасписаниеE", typeof(IIS.Legkaaya.Расписание));
                }
            }
            
            /// <summary>
            /// "РасписаниеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасписаниеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасписаниеL", typeof(IIS.Legkaaya.Расписание));
                }
            }
        }
    }
}
