//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Legkaaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сведения.
    /// </summary>
    // *** Start programmer edit section *** (Сведения CustomAttributes)

    // *** End programmer edit section *** (Сведения CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СведенияE", new string[] {
            "Номер as \'Номер\'",
            "Клетка as \'Клетка\'",
            "Клетка.НомерКлетки as \'Клетка\'",
            "Вид as \'Вид\'",
            "Вид.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Вид.Наименование"})]
    [MasterViewDefineAttribute("СведенияE", "Клетка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Тип")]
    [MasterViewDefineAttribute("СведенияE", "Вид", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Сведения : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Legkaaya.Клетка fКлетка;
        
        private IIS.Legkaaya.Вид fВид;
        
        private IIS.Legkaaya.Животные fЖивотные;
        
        // *** Start programmer edit section *** (Сведения CustomMembers)

        // *** End programmer edit section *** (Сведения CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Номер CustomAttributes)

        // *** End programmer edit section *** (Сведения.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Номер Get start)

                // *** End programmer edit section *** (Сведения.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Сведения.Номер Get end)

                // *** End programmer edit section *** (Сведения.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Номер Set start)

                // *** End programmer edit section *** (Сведения.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Сведения.Номер Set end)

                // *** End programmer edit section *** (Сведения.Номер Set end)
            }
        }
        
        /// <summary>
        /// Сведения.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Вид CustomAttributes)

        // *** End programmer edit section *** (Сведения.Вид CustomAttributes)
        [PropertyStorage(new string[] {
                "Вид"})]
        [NotNull()]
        public virtual IIS.Legkaaya.Вид Вид
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Вид Get start)

                // *** End programmer edit section *** (Сведения.Вид Get start)
                IIS.Legkaaya.Вид result = this.fВид;
                // *** Start programmer edit section *** (Сведения.Вид Get end)

                // *** End programmer edit section *** (Сведения.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Вид Set start)

                // *** End programmer edit section *** (Сведения.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (Сведения.Вид Set end)

                // *** End programmer edit section *** (Сведения.Вид Set end)
            }
        }
        
        /// <summary>
        /// Сведения.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Клетка CustomAttributes)

        // *** End programmer edit section *** (Сведения.Клетка CustomAttributes)
        [PropertyStorage(new string[] {
                "Клетка"})]
        [NotNull()]
        public virtual IIS.Legkaaya.Клетка Клетка
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Клетка Get start)

                // *** End programmer edit section *** (Сведения.Клетка Get start)
                IIS.Legkaaya.Клетка result = this.fКлетка;
                // *** Start programmer edit section *** (Сведения.Клетка Get end)

                // *** End programmer edit section *** (Сведения.Клетка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Клетка Set start)

                // *** End programmer edit section *** (Сведения.Клетка Set start)
                this.fКлетка = value;
                // *** Start programmer edit section *** (Сведения.Клетка Set end)

                // *** End programmer edit section *** (Сведения.Клетка Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Legkaaya.Животные.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Животные CustomAttributes)

        // *** End programmer edit section *** (Сведения.Животные CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Животные"})]
        public virtual IIS.Legkaaya.Животные Животные
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Животные Get start)

                // *** End programmer edit section *** (Сведения.Животные Get start)
                IIS.Legkaaya.Животные result = this.fЖивотные;
                // *** Start programmer edit section *** (Сведения.Животные Get end)

                // *** End programmer edit section *** (Сведения.Животные Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Животные Set start)

                // *** End programmer edit section *** (Сведения.Животные Set start)
                this.fЖивотные = value;
                // *** Start programmer edit section *** (Сведения.Животные Set end)

                // *** End programmer edit section *** (Сведения.Животные Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СведенияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СведенияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СведенияE", typeof(IIS.Legkaaya.Сведения));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Сведения.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСведения CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСведения CustomAttributes)
    public class DetailArrayOfСведения : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Legkaaya.DetailArrayOfСведения members)

        // *** End programmer edit section *** (IIS.Legkaaya.DetailArrayOfСведения members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Сведения by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Сведения.
        /// </summary>
        public DetailArrayOfСведения(IIS.Legkaaya.Животные fЖивотные) : 
                base(typeof(Сведения), ((ICSSoft.STORMNET.DataObject)(fЖивотные)))
        {
        }
        
        public IIS.Legkaaya.Сведения this[int index]
        {
            get
            {
                return ((IIS.Legkaaya.Сведения)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Legkaaya.Сведения dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
